### PR TITLE
Fix some package imports, roxygen documentation

### PR DESCRIPTION
**Pull request by beansrowning**
Hello!

I stumbled upon your package and saw that you were trying to resolve some package dependency issues. I forked your repo and added imports from `sf` and `magrittr` automatically and made a few changes so the package passes `R CMD check`. I figured I'd open a PR if you were interested.

I had some other ideas as well (pulling only the latest CSV data using system date and a tryCatch loop, rather than having to specify explicitly), but this seemed like your most immediate ask.

### CODE REVIEW

**Comment by microly** [comment]
Thanks!
Good work!

When I started this work, I think this is just a game...
I try to make this package so simple that others do not have to install this package! :)
They can just take away the R code and data files to their own package.

With your kind help, I think it is the time that make it a real package, thanks~

**Comment by microly** [comment]
Any ideas and prs are welcome!
It looks good to me that pull the latest data automatically.
Just do it!

**Comment by beansrowning** [comment]
Glad to hear it! Yeah, I would be happy to contribute to some other things as well as I have time. I'll submit another PR if something looks good.

**Comment by microly** [comment]
OK, thank you so much~

**Pull request merged**
